version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/nginx.dockerfile
    ports:
      - "8097:80"
    networks:
      - internal
    volumes:
      - ./:/var/www/crmapp
  fpm:
    build:
      context: .
      dockerfile: ./docker/php/fpm.dockerfile
    volumes:
      - ./:/var/www/crmapp
    networks:
      - internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=Docker
  pgsql:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=crmapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - internal
    volumes:
      - ./var/db-data:/var/lib/postgresql/data
networks:
  internal: