version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/nginx.dockerfile
    ports:
      - "8097:80"
    networks:
      - internal
    volumes:
      - ./:/var/www/crmapp
  fpm:
    build:
      context: .
      dockerfile: ./docker/php/fpm.dockerfile
    volumes:
      - ./:/var/www/crmapp
    networks:
      - internal

networks:
  internal: